spring.application.name=oficina
spring.datasource.url=jdbc:postgresql://localhost:5432/oficina_db_2
spring.datasource.username=postgres
spring.datasource.password=Thata@95
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=create-drop