apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-api-config
  namespace: oficina
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/oficina_db_2
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  SPRING_FLYWAY_BASELINE_VERSION: "0"
  SPRING_FLYWAY_VALIDATE_ON_MIGRATE: "true"
  SECURITY_JWT_EXPIRATION_SECONDS: "3600"
