apiVersion: v1
kind: Secret
metadata:
  name: oficina-api-secret
  namespace: oficina
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: troque_aqui
  SECURITY_JWT_SECRET: troque_por_uma_chave_segura_com_32_bytes_ou_mais
