apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  namespace: oficina
spec:
  type: NodePort
  selector:
    app: oficina-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
