apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: oficina
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
